// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/proto/method.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method   int32 `protobuf:"varint,1,opt,name=Method,proto3" json:"Method,omitempty"`
	WaitTime int32 `protobuf:"varint,2,opt,name=WaitTime,proto3" json:"WaitTime,omitempty"`
}

func (x *MethodRequest) Reset() {
	*x = MethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_method_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodRequest) ProtoMessage() {}

func (x *MethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_method_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodRequest.ProtoReflect.Descriptor instead.
func (*MethodRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_method_proto_rawDescGZIP(), []int{0}
}

func (x *MethodRequest) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *MethodRequest) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

type MethodUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
}

func (x *MethodUsers) Reset() {
	*x = MethodUsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_method_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodUsers) ProtoMessage() {}

func (x *MethodUsers) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_method_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodUsers.ProtoReflect.Descriptor instead.
func (*MethodUsers) Descriptor() ([]byte, []int) {
	return file_pkg_proto_method_proto_rawDescGZIP(), []int{1}
}

func (x *MethodUsers) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

type MethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32          `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response string         `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Error    string         `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Count    int32          `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Users    []*MethodUsers `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *MethodResponse) Reset() {
	*x = MethodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_method_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodResponse) ProtoMessage() {}

func (x *MethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_method_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodResponse.ProtoReflect.Descriptor instead.
func (*MethodResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_method_proto_rawDescGZIP(), []int{2}
}

func (x *MethodResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MethodResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *MethodResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MethodResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MethodResponse) GetUsers() []*MethodUsers {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_pkg_proto_method_proto protoreflect.FileDescriptor

var file_pkg_proto_method_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x43, 0x0a, 0x0d,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x57, 0x61, 0x69, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0x2c, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x55, 0x73, 0x65, 0x72, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x97, 0x01, 0x0a, 0x0e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x32, 0x42, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_proto_method_proto_rawDescOnce sync.Once
	file_pkg_proto_method_proto_rawDescData = file_pkg_proto_method_proto_rawDesc
)

func file_pkg_proto_method_proto_rawDescGZIP() []byte {
	file_pkg_proto_method_proto_rawDescOnce.Do(func() {
		file_pkg_proto_method_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_method_proto_rawDescData)
	})
	return file_pkg_proto_method_proto_rawDescData
}

var file_pkg_proto_method_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_method_proto_goTypes = []interface{}{
	(*MethodRequest)(nil),  // 0: pb.MethodRequest
	(*MethodUsers)(nil),    // 1: pb.MethodUsers
	(*MethodResponse)(nil), // 2: pb.MethodResponse
}
var file_pkg_proto_method_proto_depIdxs = []int32{
	1, // 0: pb.MethodResponse.users:type_name -> pb.MethodUsers
	0, // 1: pb.MethodService.Method:input_type -> pb.MethodRequest
	2, // 2: pb.MethodService.Method:output_type -> pb.MethodResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_method_proto_init() }
func file_pkg_proto_method_proto_init() {
	if File_pkg_proto_method_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_method_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_method_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodUsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_method_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_method_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_method_proto_goTypes,
		DependencyIndexes: file_pkg_proto_method_proto_depIdxs,
		MessageInfos:      file_pkg_proto_method_proto_msgTypes,
	}.Build()
	File_pkg_proto_method_proto = out.File
	file_pkg_proto_method_proto_rawDesc = nil
	file_pkg_proto_method_proto_goTypes = nil
	file_pkg_proto_method_proto_depIdxs = nil
}
