// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"method_svc/pkg/api"
	"method_svc/pkg/api/service"
	"method_svc/pkg/client"
	"method_svc/pkg/config"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	authServiceClient, err := client.InitAuthClient(c)
	if err != nil {
		return nil, err
	}
	authClient := client.NewAuthClient(authServiceClient)
	methodServiceServer := service.NewMethodService(authClient)
	server, err := api.NewGrpcServe(c, methodServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
