// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"auth_svc/pkg/api"
	"auth_svc/pkg/api/service"
	"auth_svc/pkg/config"
	"auth_svc/pkg/db"
	"auth_svc/pkg/repository"
)

// Injectors from wire.go:

func InitializeServe(c *config.Config) (*api.Server, error) {
	gormDB, err := db.Initdb(c)
	if err != nil {
		return nil, err
	}
	client, err := db.InitRedis(c)
	if err != nil {
		return nil, err
	}
	authRepo := repository.NewauthRepo(gormDB, client)
	authServiceServer := service.NewAuthService(authRepo)
	server, err := api.NewGrpcServe(c, authServiceServer)
	if err != nil {
		return nil, err
	}
	return server, nil
}
